[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    UnBondPeriod = 144000
    MinStepValue = "100000000000000000000"
    AuctionEnableEpoch = 100000000000
    StakeEnableEpoch = 79
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 270
    NodesToSelectInAuction = 270
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1yy4hnuugmd3245m4d0qxlsgzqv55yeuu5y5r99p8lcj2436vv0nq6drqhc"
    EnabledEpoch = 100000000000

[GovernanceSystemSCConfig]
	ProposalCost = "5000000000000000000" #5 eGLD
	NumNodes     = 500
	MinQuorum    = 400
	MinPassThreshold = 300
	MinVetoThreshold = 50
    EnabledEpoch = 100000000000
